-- TABLES -- 

CREATE TABLE Authors(
author_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
author_name VARCHAR2(255) NOT NULL,
genre VARCHAR2(100),
date_of_birth DATE,
nationality VARCHAR2(100),
website VARCHAR2(255)
);

create table Books( 
book_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
title VARCHAR2(255) NOT NULL, 
author_id NUMBER REFERENCES Authors(author_id)NOT NULL,
genre VARCHAR2(100), 
Publisher VARCHAR(255),
publication_date DATE, 
quantity_available NUMBER(5) DEFAULT 0 CHECK(quantity_available >= 0), 
quantity_borrowed NUMBER(5) DEFAULT 0 CHECK (quantity_borrowed >= 0) ); 

CREATE TABLE Members( 
member_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
first_name VARCHAR2(100) NOT NULL, 
last_name VARCHAR2(100) NOT NULL, 
email VARCHAR2(100) UNIQUE NOT NULL, 
phone_number VARCHAR2(15) NOT NULL, 
address VARCHAR2(255), 
membership_date DATE DEFAULT SYSDATE NOT NULL, 
renewal_date DATE, 
membership_status VARCHAR2(20) DEFAULT 'active' CHECK (membership_status IN('ACTIVE', 'EXPIRED', 'SUSPENDED')) ); 

CREATE TABLE Staffs( 
staff_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
first_name VARCHAR2(100) NOT NULL, 
last_name VARCHAR2(100) NOT NULL, 
phone VARCHAR2(15), 
email VARCHAR2(100), 
address VARCHAR2(255), 
hire_date DATE NOT NULL, 
salary NUMBER(10, 2) NOT NULL, 
department VARCHAR2(100) NOT NULL ); 

CREATE TABLE Transactions ( 
transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, 
book_id NUMBER NOT NULL REFERENCES Books(book_id), 
member_id NUMBER NOT NULL REFERENCES Members(member_id), 
staff_id NUMBER NOT NULL REFERENCES Staffs(staff_id), 
borrow_date DATE DEFAULT SYSDATE NOT NULL, 
book_due_date DATE NOT NULL, 
book_return_date DATE, 
status VARCHAR2(15) DEFAULT 'borrowed' CHECK (status IN ('borrowed', 'returned')) )
late_charge NUMBER(10,2) DEFAULT 0, 
late_charge_due NUMBER(10,2) DEFAULT 0 CHECK (fine_due >= 0)
payment_mode VARCHAR2(20) NULL CHECK (UPPER(payment_mode) IN ('Cash', 'Card', 'UPI')); 


-- PACKAGE -- 
-- Specification -- 

CREATE OR REPLACE PACKAGE LibraryManagement  
IS  
PROCEDURE BorrowBook ( 
	p_book_id IN Books.book_id%Type, 
    p_member_id IN Members.member_id%Type, 
    p_staff_id IN Staffs.staff_id%Type, 
    p_due_date IN Transactions.book_due_date%Type 
    ); 

PROCEDURE ReturnBook(
	p_transaction_id IN Transactions.transaction_id%type);  
    
PROCEDURE PayFine(
	p_transaction_id IN Transactions.transaction_id%type,
	p_payment_mode IN Transactions.payment_mode%Type,
	p_amount_paid IN NUMBER);  

END LibraryManagement;  
/ 

-- Body -- 

CREATE OR REPLACE PACKAGE BODY LibraryManagement  
IS  
-- procedure for borrowing the book -- 

PROCEDURE BorrowBook( 
	p_book_id IN Books.book_id%Type, 
    p_member_id IN Members.member_id%Type, 
    p_staff_id IN Staffs.staff_id%Type, 
    p_due_date IN Transactions.book_due_date%Type
    )  
IS  
	v_available_quantity NUMBER;
	v_transaction_id Transactions.transaction_id%Type; 
BEGIN 
	SELECT quantity_available INTO v_available_quantity 
	FROM Books 
	WHERE book_id = p_book_id; 
	
	if v_available_quantity <= 0 THEN 
	RAISE_APPLICATION_ERROR(-20001, 'Book is not available in stock'); 
	END IF; 

	INSERT INTO Transactions(book_id, member_id, staff_id, book_due_date)  
	VALUES(p_book_id, p_member_id, p_staff_id, sysdate + 14)
	RETURNING transaction_id INTO v_transaction_id; 
               
	UPDATE Books 
	SET quantity_available = quantity_available - 1, 
		quantity_borrowed = quantity_borrowed + 1 
	WHERE book_id = p_book_id; 
	DBMS_OUTPUT.PUT_LINE('Book borrowed successfully! Transaction id: ' || v_transaction_id) ; 
    Commit; 
               
	EXCEPTION 
		WHEN OTHERS THEN 
		DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM); 
        Rollback; 
               
		END BorrowBook; 
-- procedure for returning the book -- 

PROCEDURE ReturnBook( 
    p_transaction_id IN Transactions.transaction_id%type) 
IS 
    v_book_id Transactions.book_id%Type; 
	v_member_id Transactions.member_id%Type;  
	v_due_date Transactions.book_due_date%Type;
	v_return_date Date := sysdate;
	v_late_charge NUMBER(10,2) := 0;
	v_status Transactions.status%Type;  
BEGIN 
	SELECT book_id, member_id, book_due_date, status 
	INTO v_book_id, v_member_id, v_due_date, v_status 
	FROM Transactions 
	WHERE transaction_id = p_transaction_id AND status = 'borrowed'; 
     
	-- Late charge calculation --
	IF  v_return_date > v_due_date THEN  
		v_late_charge := (v_return_date - v_due_date)* 10;
    END IF;
	
		UPDATE Transactions 
		SET book_return_date = v_return_date, status = 'returned', late_charge = v_late_charge, late_charge_due = v_late_charge
		WHERE transaction_id = p_transaction_id;
         
        DBMS_OUTPUT.PUT_LINE('Book returned successfully! Late charge pending: ' || v_late_charge); 
        Commit; 
         
	EXCEPTION 
		WHEN NO_DATA_FOUND THEN 
			RETURN; 
			DBMS_OUTPUT.PUT_LINE('ERROR: Transaction does not exist or Invalid'); 
		WHEN OTHERS THEN 
			Rollback; 
			DBMS_OUTPUT.PUT_LINE('Error: ' || SQLERRM); 
         
END ReturnBook; 

-- procedure to payfine -- 
 
PROCEDURE PayFine(
	p_transaction_id IN Transactions.transaction_id%type,
	p_payment_mode IN Transactions.payment_mode%Type,
	p_amount_paid IN NUMBER) 
IS 
	v_late_charge_due Transactions.late_charge_due%Type;
	v_new_late_charge_due NUMBER; 
BEGIN 
	SELECT late_charge_due INTO v_late_charge_due 
	FROM Transactions
	WHERE transaction_id = p_transaction_id;
		
	-- check if partial or full payment --
	IF p_amount_paid < v_late_charge_due THEN
	v_new_late_charge_due := v_late_charge_due - p_amount_paid;
	
		UPDATE Transactions 
		SET late_charge_due = v_new_late_charge_due
		WHERE transaction_id = p_transaction_id; 
		DBMS_OUTPUT.PUT_LINE('Partial payment received. Remaining fine: ' || v_new_late_charge_due);
	ELSE 
		UPDATE Transactions 
		SET late_charge_due = 0
		WHERE transaction_id = p_transaction_id;
		DBMS_OUTPUT.PUT_LINE('Full payment paid');
	END IF;
	
		UPDATE Transactions
		SET payment_mode = UPPER(p_payment_mode)
		WHERE transaction_id = p_transaction_id;
		COMMIT;
		 
    EXCEPTION 
		WHEN NO_DATA_FOUND THEN
			DBMS_OUTPUT.PUT_LINE('ERROR: Transaction ID not found');
        RETURN;
		
        WHEN OTHERS THEN 
            DBMS_OUTPUT.PUT_LINE('ERROR: ' || SQLERRM); 
            Rollback;  
END PayFine; 
END LibraryManagement; 

-- Triggers -- 

CREATE OR REPLACE TRIGGER UpdateBookQuantityAfterReturn  
AFTER UPDATE OF status ON Transactions  
FOR EACH ROW  
BEGIN 
	IF :NEW.status = 'returned' THEN  
		UPDATE Books  
		SET quantity_available = quantity_available + 1, quantity_borrowed = quantity_borrowed - 1 
		WHERE book_id = :NEW.book_id;  
	END IF; 
 END UpdateBookQuantityAfterReturn; 


-- INSERTS -- 
-- BOOKS -- 

INSERT INTO Books (title, author_id, genre, Publisher, publication_date, quantity_available, quantity_borrowed)
SELECT 'The God of Small Things', author_id, 'Fiction', 'Penguin Random House', TO_DATE('1997', 'YYYY'), 5, 5 FROM Authors WHERE author_name = 'Arundhati Roy';

INSERT INTO Books (title, author_id, genre, Publisher, publication_date, quantity_available, quantity_borrowed)
SELECT 'Wings of Fire', author_id, 'Autobiography', 'HarperCollins', TO_DATE('1999', 'YYYY'), 8, 2 FROM Authors WHERE author_name = 'A.P.J. Abdul Kalam';

INSERT INTO Books (title, author_id, genre, Publisher, publication_date, quantity_available, quantity_borrowed)
SELECT 'The White Tiger', author_id, 'Fiction', 'Macmillan', TO_DATE('2008', 'YYYY'), 2, 3 FROM Authors WHERE author_name = 'Aravind Adiga';

INSERT INTO Books (title, author_id, genre, Publisher, publication_date, quantity_available, quantity_borrowed)
SELECT 'India After Gandhi', author_id, 'History', 'Oxford University Press', TO_DATE('2007', 'YYYY'), 6, 1 FROM Authors WHERE author_name = 'Ramachandra Guha';

INSERT INTO Books (title, author_id, genre, Publisher, publication_date, quantity_available, quantity_borrowed)
SELECT 'The Alchemist', author_id, 'Fiction', 'HarperOne', TO_DATE('1988', 'YYYY'), 10, 0 FROM Authors WHERE author_name = 'Paulo Coelho';

INSERT INTO Books (title, author_id, genre, Publisher, publication_date, quantity_available, quantity_borrowed)
SELECT 'The Great Gatsby', author_id, 'Fiction', 'Scribner', TO_DATE('1925', 'YYYY'), 10, 3 FROM Authors WHERE author_name = 'F. Scott Fitzgerald';

INSERT INTO Books (title, author_id, genre, Publisher, publication_date, quantity_available, quantity_borrowed)
SELECT '1984', author_id, 'Dystopian', 'Secker and Warburg', TO_DATE('1949', 'YYYY'), 5, 3 FROM Authors WHERE author_name = 'George Orwell';

INSERT INTO Books (title, author_id, genre, Publisher, publication_date, quantity_available, quantity_borrowed)
SELECT 'To Kill a Mockingbird', author_id, 'Fiction', 'J.B. Lippincott and Co.', TO_DATE('1960', 'YYYY'), 8, 2 FROM Authors WHERE author_name = 'Harper Lee';

INSERT INTO Books (title, author_id, genre, Publisher, publication_date, quantity_available, quantity_borrowed)
SELECT 'The Catcher in the Rye', author_id, 'Fiction', 'Little, Brown and Company', TO_DATE('1951', 'YYYY'), 6, 4 FROM Authors WHERE author_name = 'J.D. Salinger';

INSERT INTO Books (title, author_id, genre, Publisher, publication_date, quantity_available, quantity_borrowed)
SELECT 'Moby-Dick', author_id, 'Adventure', 'Richard Bentley', TO_DATE('1851', 'YYYY'), 7, 1 FROM Authors WHERE author_name = 'Herman Melville';

INSERT INTO Books (title, author_id, genre, Publisher, publication_date, quantity_available, quantity_borrowed)
SELECT 'War and Peace', author_id, 'Historical Fiction', 'The Russian Messenger', TO_DATE('1869', 'YYYY'), 12, 5 FROM Authors WHERE author_name = 'Leo Tolstoy';

INSERT INTO Books (title, author_id, genre, Publisher, publication_date, quantity_available, quantity_borrowed)
SELECT 'Pride and Prejudice', author_id, 'Romance', 'T. Egerton', TO_DATE('1813', 'YYYY'), 9, 1 FROM Authors WHERE author_name = 'Jane Austen';

-- Authors --

INSERT INTO Authors (author_name, genre, date_of_birth, nationality, website) VALUES
('Arundhati Roy', 'Fiction', TO_DATE('1961-11-24', 'YYYY-MM-DD'), 'Indian', 'https://www.arundhatiroy.org');
INSERT INTO Authors (author_name, genre, date_of_birth, nationality, website) VALUES
('A.P.J. Abdul Kalam', 'Non-fiction', TO_DATE('1931-10-15', 'YYYY-MM-DD'), 'Indian', 'https://www.abdulkalam.com');
INSERT INTO Authors (author_name, genre, date_of_birth, nationality, website) VALUES
('Aravind Adiga', 'Fiction', TO_DATE('1974-10-23', 'YYYY-MM-DD'), 'Indian', 'https://www.aravindadiga.com');
INSERT INTO Authors (author_name, genre, date_of_birth, nationality, website) VALUES
('Ramachandra Guha', 'History', TO_DATE('1958-04-29', 'YYYY-MM-DD'), 'Indian', 'https://www.ramachandraguha.in');
INSERT INTO Authors (author_name, genre, date_of_birth, nationality, website) VALUES
('Paulo Coelho', 'Fiction', TO_DATE('1947-08-24', 'YYYY-MM-DD'), 'Brazilian', 'https://www.paulocoelho.com');
INSERT INTO Authors (author_name, genre, date_of_birth, nationality, website) VALUES
('F. Scott Fitzgerald', 'Fiction', TO_DATE('1896-09-24', 'YYYY-MM-DD'), 'American', 'https://www.fscottfitzgerald.org');
INSERT INTO Authors (author_name, genre, date_of_birth, nationality, website) VALUES
('George Orwell', 'Dystopian', TO_DATE('1903-06-25', 'YYYY-MM-DD'), 'British', 'https://www.georgeorwell.org');
INSERT INTO Authors (author_name, genre, date_of_birth, nationality, website) VALUES
('Harper Lee', 'Fiction', TO_DATE('1926-04-28', 'YYYY-MM-DD'), 'American', 'https://www.harperlee.com');
INSERT INTO Authors (author_name, genre, date_of_birth, nationality, website) VALUES
('J.D. Salinger', 'Fiction', TO_DATE('1919-01-01', 'YYYY-MM-DD'), 'American', 'https://www.jd-salinger.com');
INSERT INTO Authors (author_name, genre, date_of_birth, nationality, website) VALUES
('Herman Melville', 'Fiction', TO_DATE('1819-08-01', 'YYYY-MM-DD'), 'American', 'https://www.hermanmelville.org');
INSERT INTO Authors (author_name, genre, date_of_birth, nationality, website) VALUES
('Leo Tolstoy', 'Historical Fiction', TO_DATE('1828-09-09', 'YYYY-MM-DD'), 'Russian', 'https://www.leotolstoy.com');
INSERT INTO Authors (author_name, genre, date_of_birth, nationality, website) VALUES
('Jane Austen', 'Romance', TO_DATE('1775-12-16', 'YYYY-MM-DD'), 'British', 'https://www.janeausten.org');


-- Members -- 

 INSERT INTO MEMBERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, MEMBERSHIP_DATE, RENEWAL_DATE, MEMBERSHIP_STATUS) VALUES 
 ('Rajesh','Kumar','rajesh.kumar@example.com','9876543210','Delhi',to_date('2022-01-15', 'YYYY-MM-DD'),to_date('2023-01-15', 'YYYY-MM-DD'),'EXPIRED');  

INSERT INTO MEMBERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, MEMBERSHIP_DATE, RENEWAL_DATE, MEMBERSHIP_STATUS) VALUES 
('Anita','Sharma','anita.sharma@example.com','8765432109','Mumbai',to_date('2021-10-10', 'YYYY-MM-DD'),to_date('2022-10-10', 'YYYY-MM-DD'),'EXPIRED');  

INSERT INTO MEMBERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, MEMBERSHIP_DATE, RENEWAL_DATE, MEMBERSHIP_STATUS) VALUES 
('Sunil','Verma','sunil.verma@example.com','7654321098','Kolkata',to_date('2023-04-20', 'YYYY-MM-DD'),to_date('2025-04-20', 'YYYY-MM-DD'),'ACTIVE');  

INSERT INTO MEMBERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, MEMBERSHIP_DATE, RENEWAL_DATE, MEMBERSHIP_STATUS) VALUES 
('Meera','Nair','meera.nair@example.com','6543210987','Chennai',to_date('2020-08-01', 'YYYY-MM-DD'),null,'SUSPENDED');  

INSERT INTO MEMBERS (FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, ADDRESS, MEMBERSHIP_DATE, RENEWAL_DATE, MEMBERSHIP_STATUS) VALUES 
('Priya','Singh','priya.singh@example.com','5432109876','Bangalore',to_date('2023-06-12', 'YYYY-MM-DD'),to_date('2025-06-12', 'YYYY-MM-DD'),'ACTIVE'); 

INSERT INTO Members(first_name, last_name, email, phone_number, address, membership_date, renewal_date, membership_status) VALUES 
('Pankaj', 'Kishore', 'pankaj.kishore@example.com', '9875553210', 'Delhi', TO_DATE('2018-05-01', 'YYYY-MM-DD'), TO_DATE('2025-05-01', 'YYYY-MM-DD'), 'ACTIVE'); 

-- staffs -- 

INSERT INTO Staffs(first_name, last_name, phone, email, address, hire_date, salary, department) VALUES 
('Amit', 'Gupta', '9998887771', 'amit.gupta@library.com', 'Delhi, India', TO_DATE('2015-05-10', 'YYYY-MM-DD'), 45000, 'Administration');  

INSERT INTO Staffs(first_name, last_name, phone, email, address, hire_date, salary, department) VALUES 
('Nisha', 'Kapoor', '8887776662', 'nisha.kapoor@library.com', 'Mumbai, India', TO_DATE('2018-03-22', 'YYYY-MM-DD'), 40000, 'Library Assistance');  

INSERT INTO Staffs(first_name, last_name, phone, email, address, hire_date, salary, department) VALUES 
('Ravi', 'Chauhan', '7776665553', 'ravi.chauhan@library.com', 'Lucknow, India', TO_DATE('2020-11-15', 'YYYY-MM-DD'), 35000, 'Security');  

INSERT INTO Staffs(first_name, last_name, phone, email, address, hire_date, salary, department) VALUES 
('Sneha', 'Reddy', '6665554444', 'sneha.reddy@library.com', 'Hyderabad, India', TO_DATE('2019-06-01', 'YYYY-MM-DD'), 50000, 'Technology Support'); 

-- Transactions -- 

INSERT INTO Transactions (book_id, member_id, staff_id, borrow_date, book_due_date, book_return_date, status, late_charge_due, payment_mode)
VALUES 
(1, 1, 1, TO_DATE('2023-11-15', 'YYYY-MM-DD'), TO_DATE('2023-11-25', 'YYYY-MM-DD'), NULL, 'borrowed', 0, NULL); -- not yet

INSERT INTO Transactions (book_id, member_id, staff_id, borrow_date, book_due_date, book_return_date, status, late_charge_due, payment_mode)
VALUES 
(2, 2, 2, TO_DATE('2023-10-01', 'YYYY-MM-DD'), TO_DATE('2023-10-10', 'YYYY-MM-DD'), TO_DATE('2023-10-12', 'YYYY-MM-DD'), 'returned', 20, 'Card'); -- late

INSERT INTO Transactions (book_id, member_id, staff_id, borrow_date, book_due_date, book_return_date, status, late_charge_due, payment_mode)
VALUES 
(3, 3, 3, TO_DATE('2023-12-01', 'YYYY-MM-DD'), TO_DATE('2023-12-10', 'YYYY-MM-DD'), NULL, 'borrowed', 0, NULL); -- not yet

INSERT INTO Transactions (book_id, member_id, staff_id, borrow_date, book_due_date, book_return_date, status, late_charge_due, payment_mode)
VALUES 
(4, 4, 4, TO_DATE('2023-10-01', 'YYYY-MM-DD'), TO_DATE('2023-10-10', 'YYYY-MM-DD'), TO_DATE('2023-10-08', 'YYYY-MM-DD'), 'returned', 0, NULL); -- early

INSERT INTO Transactions (book_id, member_id, staff_id, borrow_date, book_due_date, book_return_date, status, late_charge_due, payment_mode)
VALUES 
(5, 5, 1, TO_DATE('2023-11-28', 'YYYY-MM-DD'), TO_DATE('2023-12-08', 'YYYY-MM-DD'), NULL, 'borrowed', 0, NULL); -- not yet

INSERT INTO Transactions (book_id, member_id, staff_id, borrow_date, book_due_date, book_return_date, status, late_charge_due, payment_mode)
VALUES 
(6, 1, 2, TO_DATE('2023-09-05', 'YYYY-MM-DD'), TO_DATE('2023-09-15', 'YYYY-MM-DD'), TO_DATE('2023-09-17', 'YYYY-MM-DD'), 'returned', 20, 'Cash'); -- late

INSERT INTO Transactions (book_id, member_id, staff_id, borrow_date, book_due_date, book_return_date, status, late_charge_due, payment_mode)
VALUES 
(7, 2, 3, TO_DATE('2023-08-10', 'YYYY-MM-DD'), TO_DATE('2023-08-20', 'YYYY-MM-DD'), TO_DATE('2023-08-21', 'YYYY-MM-DD'), 'returned', 10, 'UPI'); -- late

INSERT INTO Transactions (book_id, member_id, staff_id, borrow_date, book_due_date, book_return_date, status, late_charge_due, payment_mode)
VALUES 
(8, 3, 4, TO_DATE('2023-07-01', 'YYYY-MM-DD'), TO_DATE('2023-07-10', 'YYYY-MM-DD'), TO_DATE('2023-07-12', 'YYYY-MM-DD'), 'returned', 20, 'Card'); -- late

INSERT INTO Transactions (book_id, member_id, staff_id, borrow_date, book_due_date, book_return_date, status, late_charge_due, payment_mode)
VALUES 
(9, 4, 1, TO_DATE('2023-11-05', 'YYYY-MM-DD'), TO_DATE('2023-11-15', 'YYYY-MM-DD'), TO_DATE('2023-11-17', 'YYYY-MM-DD'), 'returned', 20, 'Cash'); -- late

INSERT INTO Transactions (book_id, member_id, staff_id, borrow_date, book_due_date, book_return_date, status, late_charge_due, payment_mode)
VALUES 
(10, 5, 2, TO_DATE('2023-06-20', 'YYYY-MM-DD'), TO_DATE('2023-06-30', 'YYYY-MM-DD'), TO_DATE('2023-07-02', 'YYYY-MM-DD'), 'returned', 20, 'UPI'); -- late

INSERT INTO Transactions (book_id, member_id, staff_id, borrow_date, book_due_date, book_return_date, status, late_charge_due, payment_mode)
VALUES 
(4, 4, 1, TO_DATE('2022-12-12', 'YYYY-MM-DD'), TO_DATE('2022-12-26', 'YYYY-MM-DD'), TO_DATE('2022-12-24', 'YYYY-MM-DD'), 'returned', 0, NULL); -- early

INSERT INTO Transactions (book_id, member_id, staff_id, borrow_date, book_due_date, book_return_date, status, late_charge_due, payment_mode)
VALUES 
(4, 4, 2, TO_DATE('2023-02-01', 'YYYY-MM-DD'), TO_DATE('2023-02-15', 'YYYY-MM-DD'), TO_DATE('2023-02-12', 'YYYY-MM-DD'), 'returned', 0, NULL); -- early

INSERT INTO Transactions (book_id, member_id, staff_id, borrow_date, book_due_date, book_return_date, status, late_charge_due, payment_mode)
VALUES 
(4, 4, 4, TO_DATE('2023-10-05', 'YYYY-MM-DD'), TO_DATE('2023-10-19', 'YYYY-MM-DD'), TO_DATE('2023-10-08', 'YYYY-MM-DD'), 'returned', 0, NULL); -- early



  
-- 

 